---
deployment:
  tasks:
    - source ~/virtualenv/django_app/3.12/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate --noinput
    - python manage.py collectstatic --noinput
   
